### ISSUE TITLE
Overall review of SDK docs v5.2.0 

### ISSUE THREAD

**Issue by chris529** [LiskArchive/lisk-legacy-docs#1181] opened 2021-09-22 06:49 UTC
The latest version of the SDK v5.1.4 has now had a partial re-write and also contains new guides.
Therefore, after all of the new updates/additions/changes a full overall review, including the content flow, grammar, punctuation, links, etc. is required.

**Comment by Tschakki** [comment] 2022-01-28 10:14
Duplicate of #1035

**Closed as completed by Tschakki** 2022-01-28 10:14 UTC
