### ISSUE TITLE
API 1.0Which is the correct order, the coin order

### ISSUE THREAD

**Issue by haohaole** [LiskArchive/lisk-legacy-docs#130] opened 2018-12-03 07:07 UTC
curl -k -H "Content-Type: application/json" \
-X PUT -d '{"secret":"<INSERT SECRET HERE>","publicKey"="<INSERT PUBLICKEY HERE>","delegates":["<INSERT DELEGATE PUBLICKEY HERE>"]}' \
http://localhost:8000/api/accounts/delegates

This is a wrong report.?

**Comment by Tschakki** [comment] 2018-12-05 22:36
Duplicate of #131

**Closed as completed by Tschakki** 2018-12-05 22:36 UTC
